# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_auto_20171230_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_no', models.IntegerField()),
                ('file_name', models.CharField(max_length=200)),
                ('file_content', models.CharField(max_length=400)),
                ('file_path', models.CharField(max_length=200)),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
