# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_content',
            field=models.TextField(max_length=400),
        ),
    ]
